apiVersion: v1
stringData:
  alertmanagers.yaml: |
    "alertmanagers":
    - "http_config":
        "bearer_token_file": "/var/run/secrets/kubernetes.io/serviceaccount/token"
        "tls_config":
          "ca_file": "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          "server_name": "wheel-alertmanager.monitoring-stack.svc"
      "scheme": "https"
      "static_configs":
      - "dnssrv+_web._tcp.alertmanager-operated.monitoring-stack.svc"
kind: Secret
metadata:
  name: thanos-ruler-alertmanagers-config
type: Opaque

