kind: Deployment
apiVersion: apps/v1
metadata:
  name: camel-k-operator
  namespace: camel-k-operator
spec:
  template:
    spec:
      containers:
        - name: camel-k-operator
          env:
            - name: WATCH_NAMESPACE
              value: ""