portal:
  mariadb:
    primary:
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
    secondary:
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
    volumePermissions:
      enabled: false
  user-management:
    um-admin-ui:
      angular-base:
        serviceAccount:
          create: false
          name: nonroot
    um-profile-ui:
      angular-base:
        serviceAccount:
          create: false
          name: nonroot