portal:
  mariadb:
    primary:
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
    secondary:
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
    volumePermissions:
      enabled: false
