kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: console
spec:
  host: minio-console.apps.baloise.dev
  to:
    kind: Service
    name: console
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect