kind: ConfigMap
metadata:
  name: argocd-cm
apiVersion: v1
data:
  url: https://argocd.baloise.dev
  users.anonymous.enabled: 'true'
  statusbadge.enabled: 'true'
  repositories: |
    - type: helm
      url: https://registry.baloise.dev/chartrepo/library
      name: incubator-library
  dex.config: |
    connectors:
      - type: openshift
        id: openshift
        name: OpenShift
        config:
          issuer: https://api.okd.baloise.dev:6443
          clientID: system:serviceaccount:argocd:argocd-dex-server
          clientSecret: $dex.clientSecret
          redirectURI: https://argocd.baloise.dev/api/dex/callback
