kind: Deployment
apiVersion: apps/v1
metadata:
  name: argocd-redis-ha-haproxy
spec:
  template:
    spec:
      affinity: null
      securityContext:
        runAsUser: 1000600000
        runAsNonRoot: true
        fsGroup: 1000600000