apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      containers:
        - imagePullPolicy: IfNotPresent
          name: dex
          command:
            - /shared/argocd-dex
            - rundex
#            - --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          env:
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: argocd-dex-server-sa
                  key: token
      initContainers:
        - imagePullPolicy: IfNotPresent
          name: copyutil