apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.argocd: https://argocd.apps.origin.baloise.dev/api/dex/callback
  name: argocd-dex-server
