apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  url: https://argocd.baloise.dev
  users.anonymous.enabled: 'true'
  statusbadge.enabled: 'true'
  admin.enabled: 'false'
  resource.exclusions: |
    - apiGroups:
      - tekton.dev
      kinds:
      - PipelineRun
      clusters:
      - https://kubernetes.default.svc
  resource.customizations: |
    tekton.dev/PipelineRun:
      ignoreDifferences: |
        jsonPointers:
        - /
  repositories: |
    - type: helm
      url: https://registry.baloise.dev/chartrepo/library
      name: incubator-library
    - type: helm
      url: https://charts.bitnami.com/bitnami
      name: bitnami
    - type: helm
      url: https://charts.jfrog.io
      name: jfrog
  dex.config: |
    connectors:
      - type: openshift
        id: openshift
        name: OpenShift
        config:
          issuer: https://api.okd.baloise.dev:6443
          clientID: system:serviceaccount:argocd:argocd-dex-server
          clientSecret: $dex.clientSecret
          redirectURI: https://argocd.baloise.dev/api/dex/callback
  kustomize.buildOptions: --enable-helm
