apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  replicas: 3
  template:
    spec:
      affinity: null
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - name: gpg-keys-tmp
              mountPath: /app/config/gpg/keys/
      volumes:
        - name: gpg-keys-tmp
          emptyDir: {}
          defaultMode: 1274
#  template:
#    spec:
#      containers:
#        - image: 'niiku/argocd:latest'
#          name: argocd-repo-server
