kind: ConfigMap
metadata:
  name: argocd-cm
apiVersion: v1
data:
  url: https://argocd.baloise.dev
  users.anonymous.enabled: 'true'
  statusbadge.enabled: 'true'
  admin.enabled: 'false'
  resource.exclusions: |
    - apiGroups:
      - tekton.dev
      kinds:
      - PipelineRun
      clusters:
      - https://kubernetes.default.svc
  resource.customizations: |
    tekton.dev/PipelineRun:
      ignoreDifferences: |
        jsonPointers:
        - /
  repositories: |
    - type: helm
      url: https://registry.baloise.dev/chartrepo/library
      name: incubator-library
    - type: helm
      url: https://charts.bitnami.com/bitnami
      name: bitnami
  dex.config: |
    connectors:
      - type: openshift
        id: openshift
        name: OpenShift
        config:
          issuer: https://api.okd.baloise.dev:6443
          clientID: system:serviceaccount:argocd:argocd-dex-server
          clientSecret: $dex.clientSecret
          redirectURI: https://argocd.baloise.dev/api/dex/callback
  configManagementPlugins: |
  - name: kustomized-helm
    init:
      command: ["/bin/sh", "-c"]
      args: ["helm dependency build || true"]
    generate:
      command: [sh, -c]
      args: ["helm template . --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE --include-crds > all.yaml && kustomize build"]
