apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  replicas: 2
  template:
    spec:
      affinity: null
      containers:
        - name: argocd-repo-server
          imagePullPolicy: Always
          env:
            - name: ARGOCD_GPG_ENABLED
              value: "false"