apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      affinity: null
      initContainers:
        - name: rollout-extension
          image: quay.io/argoprojlabs/argocd-extension-installer:v0.0.1
          env:
          - name: EXTENSION_URL
            value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.4/extension.tar
          volumeMounts:
            - name: extensions
              mountPath: /tmp/extensions/
      containers:
        - name: argocd-server
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: extensions
              mountPath: /tmp/extensions/
          args:
            - /usr/local/bin/argocd-server
            - --insecure
            - --staticassets
            - /shared/app
            - --redis
            - "argocd-redis-ha-haproxy:6379"
      volumes:
        - name: extensions
          emptyDir: {}
