apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.telegram: |
    token: $telegram-token
  service.teams: |
    recipientUrls:
      channelName: $channel-teams-url