kind: ConfigMap
metadata:
  name: argocd-cm
apiVersion: v1
data:
  url: https://argocd.apps.origin.baloise.dev
  users.anonymous.enabled: 'true'
  statusbadge.enabled: 'true'
  dex.config: |
    connectors:
      - type: openshift
        id: openshift
        name: OpenShift
        config:
          issuer: https://api.origin.baloise.dev:6443
          clientID: system:serviceaccount:argocd:argocd-dex-server
          clientSecret: $dex.clientSecret
          redirectURI: https://argocd.apps.origin.baloise.dev/api/dex/callback
