apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      containers:
        - imagePullPolicy: IfNotPresent
          name: dex
          env:
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: argocd-dex-server-sa
                  key: token
      initContainers:
        - imagePullPolicy: IfNotPresent
          name: copyutil