apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-redis-ha-server
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1000600000
        runAsNonRoot: true
        runAsUser: 1000600000
