apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      affinity: null
      containers:
        - name: argocd-server
          imagePullPolicy: IfNotPresent
          command:
            - argocd-server
            - --insecure
            - --staticassets
            - /shared/app
            - --redis
            - "argocd-redis-ha-haproxy:6379"
