kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: argocd-application-controller
spec:
  template:
    spec:
      affinity: null
      containers:
        - name: argocd-application-controller
          imagePullPolicy: IfNotPresent