apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "usu-portal.fullname" . }}-adapter-usm
  labels:
    {{- include "usu-portal.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "usu-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "usu-portal.selectorLabels" . | nindent 8 }}
        app: usu-portal.adapter-usm
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 10 }}
      {{- end }}
      containers:
      - name: adapter-usm
        image: {{ .Values.usuportal.adapters.usm.image }}:{{ .Values.usuportal.adapters.usm.tag }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: 8011
        env:
          - name: spring.cloud.consul.enabled
            value: "false"
          - name: com.usu.keycloak.issuerUrls
            value: {{ .Values.usuportal.um.keycloakUrl | quote }}
          - name: com.usu.keycloak.authServerUrl
            value: "http://um-keycloak/auth"
          - name: com.usu.keycloak.resource
            value: vm:valuemation-web
          - name: usu.portal.vm.webServiceClient-accessTokenPortal
            value: 'CYzOpmOTp17qG80Beo0mn.o42t&?zOI=+WJ+'
          - name: usu.portal.vm.dbguid
            value: 'd8503f50-bd77-4f0f-819d-84789c161539'
          - name: usu.portal.vm.vm-version
            value: '5.3'
          - name: usu.portal.vm.web.external-url
            value: {{ .Values.usuportal.adapters.usm.webExternalUrl | quote }}
          - name: usu.portal.vm.web.internal-url
            value: {{ .Values.usuportal.adapters.usm.webInternalUrl | quote }}

