apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: camel-k-operator
bases:
  - github.com/apache/camel-k/install/setup?ref=v1.7.0
  - github.com/apache/camel-k/config/crd?ref=v1.7.0
  - github.com/apache/camel-k/install/operator?ref=v1.7.0

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: camel-k-operator-custom-resource-definitions
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: camel-k-operator
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: camel-k-operator
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env/0/valueFrom
      - op: add
        path: /spec/template/spec/containers/0/env/0/value
        value: "camel-k-resources"