apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hcloud-csi
  namespace: hcloud-csi
spec:
  encryptedData:
    token: AgAWEnybL+/M4km3i7yDq7smdP6OkkbViMRv0Do4frNJ3PK+lmGZocSUXn7gqO184DQ5KSQQ6usIO+n7c8ciM58rrTXe1ktL76g3BLZ7Xu+K9D7J80xEqbWMdp6p5ya9Fff9p9m6eyRQW5Dl+MszJHSGAejODgWOdAk7cZV3eG2Nr5Zt5srGv8btT2+2fjpjT/H8zRmTREXGJTbL4CG5ve/RrlKsWXtmU3jec7EVwl1h1iO2VfN9o3f/eroqmwPPIBGRH5NmbEgWHBR2MNgqsgQq2BgTGOi7mr9iKbFNkpv5qt+EXwms1C1wNBf/gi9kL9BFc5FOSvVWrnosv9p1BpIf5NuUiNgu3ZoXBh5COFDbL52zMVzm1AraPZ/UBXdwsqvWCjoIYqEQtlLS03jLPq3oPqR7ChKG4hjfModscJST9oH2ttSXeK3cel80BQD2MqcQpjDGNM4ykpYUpRFi/sVrO7pA4mue34pS7X0Umbo5OrqCqU/eXiT34FwS7gwjolmpjbd4IGggDgFYSXuakCsiKb04xUWH3NyOW5SPa3oudOU6RmBvc2cmeYu+hNE+MlgtX0rTQmyhPobk5d49asWxmlb+Or1h/jO2YIO2idJbRQ/bANTt4Ir/sZHeB6noU0u2ndDKgrKCdkP3mlD+McI4bCVYNoLgsmUkni5LeH4AR7qzqDvbzLTHS7YycZsFqBP7vS1JB+TyIkTZeX//42yg76eGOU5skJcGvDqWQFT0tYOPk+yG7fhIkr4p4V1VVigSeNSi0vYd9ic29QfbgxWL
  template:
    metadata:
      creationTimestamp: null
      name: hcloud-csi
      namespace: hcloud-csi
status: {}

