apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portworx-anyuid
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - anyuid
    resources:
      - securitycontextconstraints
    verbs:
      - use