apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: argoworkflow
spec:
  host: argoworkflow.baloise.dev
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: argoworkflow-server
    weight: 100
