kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-cluster-role
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - get
      - watch
      - list"
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - create
      - get
      - list
      - watch
      - delete
    apiGroups:
      - ''
    resources:
      - pods
      - pods/exec
      - pods/log
  - verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
    apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflows/finalizers
      - workflowtemplates      
      - cronworkflows
      - clusterworkflowtemplates
