apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: prometheus-operator-tls
  labels:
    prometheus: prometheus-operator
  name: prometheus-operator
spec:
  ports:
    - name: metrics
      port: 9091
      targetPort: metrics
  selector:
    app: prometheus
    prometheus: user-workload
  sessionAffinity: ClientIP

