global:
  env:
    # global.env.keycloakUrl -- (String) global value for env.keycloakUrl
    keycloakUrl: https://usu-portal.apps.baloise.dev/auth
portal:
  usuportal:
    client:
      image: artifactory-jcr.baloise.dev/usu/client
      tag: 2-4-1
    hostname: usu-portal.apps.baloise.devc
    um:
      keycloakUrl: https://usu-portal.apps.baloise.dev/auth
      profileUrl: https://usu-portal-profile.apps.baloise.dev/
      adminUrl: https://usu-portal-admin.apps.baloise.dev/
  user-management:
    user-management-service:
      env:
        kcConnection:
          externalUrl: https://usu-portal.apps.baloise.dev/auth
          internalUrl: "http://um-keycloak/auth"
    keycloak:
      extraEnv:
        # -- Explicitly specify Keycloak Frontend URL accessible by external client - needed for USM
        - name: "KEYCLOAK_FRONTEND_URL"
          value: https://usu-portal.apps.baloise.dev/auth
    um-admin-ui:
      angular-base:
        image:
          registry: artifactory-jcr.baloise.dev
          repository: usu/admin-ui
          tag: 3.0.0
        ingress:
          enabled: false        
#        serviceAccount:
#          create: false
#          name: anyuid
        env:
          apiUrl: https://usu-portal.apps.baloise.dev/user-management-service/
    um-profile-ui:
      angular-base:
        image:
          registry: artifactory-jcr.baloise.dev
          repository: usu/profile-ui
          tag: 3.0.0
        ingress:
          enabled: false
#        serviceAccount:
#          create: false
#          name: anyuid
        env:
          apiUrl: https://usu-portal.apps.baloise.dev/user-management-service/
  mariadb:
    primary:
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
    secondary:
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
    volumePermissions:
      enabled: false