apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "usu-portal.fullname" . }}-backend
  labels:
    {{- include "usu-portal.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "usu-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "usu-portal.selectorLabels" . | nindent 8 }}
        app: usu-portal.backend
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: backend
        image: {{ .Values.portalApp.backend.container.image }}:{{ .Values.portalApp.backend.container.tag }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 1000m
        env:
          - name: spring.cloud.consul.host
            value: consul-server
          - name: spring.cloud.consul.port
            value: '8500'
          - name: spring.cloud.consul.discovery.acl-token
            value: default
          - name: spring.cloud.consul.discovery.hostname
            value: {{ include "usu-portal.fullname" . }}-backend-service
          - name: spring.cloud.consul.discovery.port
            value: '80'
          - name: com.usu.keycloak.issuerUrls
            value: "https://usu-portal.apps.okd.baloise.dev/auth/"
          - name: com.usu.keycloak.authServerUrl
            value: "http://um-keycloak/auth"
          - name: external-host-whitelist
            value: 'usu.com'
          - name: spring.datasource.url
            value: 'jdbc:mariadb://ssp-mariadb-app:3307/portal'
          - name: spring.datasource.username
            valueFrom:
              secretKeyRef:
                name: portal-secrets
                key: mariadb-username
          - name: spring.datasource.password
            valueFrom:
              secretKeyRef:
                name: portal-secrets
                key: mariadb-password
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "usu-portal.fullname" . }}-backend-service
  labels:
    {{- include "usu-portal.labels" . | nindent 4 }}
    app: usu-portal.backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8120
      protocol: TCP
      name: http
  selector:
    app: usu-portal.backend
