apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "usu-portal.fullname" . }}-client
  labels:
    {{- include "usu-portal.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "usu-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "usu-portal.selectorLabels" . | nindent 8 }}
        app: usu-portal.client
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: client
        image: {{ .Values.portalApp.client.container.image }}:{{ .Values.portalApp.client.container.tag }}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 250m
        env:
          - name: CONSUL_TOKEN
            value: default
          - name: CONSUL_HOST
            value: 'consul-server'
          - name: CONSUL_PORT
            value: '8500'
          - name: CLIENT_BASE_PATH
            value: ''
          - name: KEY_CLOAK_URL
            value: "https://usu-portal.apps.okd.baloise.dev/auth/"
          - name: HELP_PAGE_URL
            value: 'https://google.com'
          - name: PROFILE_URL
            value: 'http://localhost/'
          - name: USER_MANAGEMENT_URL
            value: "http://um-keycloak/auth/"
          - name: THEME_NAME
            value: ''
          - name: FALLBACK_LANGUAGE
            value: 'en'
          - name: BACKEND_HOST
            value: {{ include "usu-portal.fullname" . }}-backend-service
          - name: BACKEND_PORT
            value: '80'
          
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "usu-portal.fullname" . }}-client-service
  labels:
    {{- include "usu-portal.labels" . | nindent 4 }}
    app: usu-portal.client
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: usu-portal.client
