---
apiVersion: v1
kind: Secret
metadata:
  name: "portal-secrets"
  labels:
{{ include "usu-portal.labels" . | indent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mariadb-username: {{ .Values.mariadb.auth.username | b64enc | quote}}
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc | quote}}
