apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader

bases:
  - https://github.com/stakater/Reloader/deployments/kubernetes?ref=v0.0.104

patchesStrategicMerge:
  - overlays/deployment.yaml