apiVersion: v1
stringData:
  config.yaml: |
    "authorization":
      "resourceAttributes":
        "apiGroup": "monitoring.coreos.com"
        "namespace": "{{ .Value }}"
        "resource": "prometheusrules"
      "rewrites":
        "byQueryParameter":
          "name": "namespace"
kind: Secret
metadata:
  labels:
    k8s-app: wheel-alertmanager
  name: alertmanager-kube-rbac-proxy
type: Opaque

