apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-acme
resources:
  - https://raw.githubusercontent.com/tnozicka/openshift-acme/bdd71b7a4b65ba6c4a15119bf1fc06d7a289efd4/deploy/cluster-wide/clusterrole.yaml
  - https://raw.githubusercontent.com/tnozicka/openshift-acme/bdd71b7a4b65ba6c4a15119bf1fc06d7a289efd4/deploy/cluster-wide/deployment.yaml
  - https://raw.githubusercontent.com/tnozicka/openshift-acme/bdd71b7a4b65ba6c4a15119bf1fc06d7a289efd4/deploy/cluster-wide/issuer-letsencrypt-live.yaml
  - https://raw.githubusercontent.com/tnozicka/openshift-acme/bdd71b7a4b65ba6c4a15119bf1fc06d7a289efd4/deploy/cluster-wide/serviceaccount.yaml
