kind: Service
apiVersion: v1
metadata:
  name: envoy-unauthenticated-prometheus-proxy
  labels:
    app: envoy-unauthenticated-prometheus-proxy
spec:
  ports:
    - name: 9091-tcp
      protocol: TCP
      port: 9091
      targetPort: 9091
  selector:
    app: envoy-unauthenticated-prometheus-proxy
  type: ClusterIP