apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: objectbuckets.objectbucket.io
spec:
  group: objectbucket.io
  names:
    kind: ObjectBucket
    listKind: ObjectBucketList
    plural: objectbuckets
    shortNames:
      - ob
      - obs
    singular: objectbucket
  preserveUnknownFields: true
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
