kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: postgres-pod
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch