apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clair-cm
  namespace: harbor
spec:
  encryptedData:
    config.yaml: AgA8Rhmhp48I7qAo3aqdpZGLAhHDosHJ45vGlDJ13zEw68nR1xr8BZvLlq5guw1YrGehjCL0zTyDcF9Y6Gnly9S0qrm+fPE49YFiRF9B6iaC9ZQqIDWO5j+eRqDOuuFwzHKkMxGU0Lq+aycxDhXXh2L2TiIuOLNzKm1R/Y7h/m2XHAxNxDBwUMnJPH11OiIn59EizfSTISB2kSKXcARC7AbQ1maf6lKdvIR1GkROBkT9VnFKbOowa7E8EOy6i5xYRLExnbgWnJ4nPk6+pUSs0UeiB5j5b/uEq3LfL70id6PH/5DmBzC22f+vY5QIrT+89VMe0bX7i9K+f7Xx8daQIIGhNDKpkPX8V1Y41UrN6P4dl6nZk7Pj4niol94q5q2Y+CPLtxXt6KzXJKRtykG38W/jvTy9zxDWMsUylKs5yBH64rpYX027nfvyl1QoBzU+x8RJXHFkaQmJmZ73oYRq7q3PobVdCRAr8BFKZ2rfiMkQUKs6tUW/QnkB+g5vS0z5xIuDne6gFIZV81Vrmjs7tPl+U6527oCxFXfQ5Q/fLFM4KE0mLqns84kfLIxS5uzwHz58jh5G6SdvQRfBiQLNuOsnxweqgc+ytuWOs9wSO6zBv3s5VL67EgCQhLOxhNQH//zkfLwQFnfKgdB/sfStQ7rcd/SvTHJyVZMBJZ1PVZrmQBv2GfU/fVnx6Me5iV7lfabDmCIwG/PMbImQOe1LYiTNkwXXCjs/vyvQD502tmfqeNCnl3Iyzkg0lHljg5ibUTeLXsokpKBW465JfRd2/JaU+4YZtu4tw3UN54spT3kiri59wYt8aSR+gzo/ovZDKQrxCBxyh1ldo6exIJ5eXcDXG8MAcyH2i3nhrLRjeZZczChZLD+shxyi84pRC/ryZldbkT76kI6kRK9DB1PsFg8UmYajH+I/Bz0DQAZdZzFuuQSd5mg+WuOqs9MbREq2n8oZ49c8XoDl+kB+mQlaZ8EE1gAp/B2uS7imUiMHTsDBkHUaKgeXlcckSwW4sq71u8EKTNbZ7gp1YqzKWP3uwdi+mlM9rk0qjRb+FTDcvSngGEupaqIgYNE7XHkaMaopEaj4oYlWBEc3Vy6bsAtARORrUXk8iX9zSwZ0fQkevdsGedKKPOjYONrhQ6F/7GuRsKItOgUsvKVms5cinBDiK9etohf2SzchLWCY9j0f+OXcpfgiunh+MMBQ7lwDuFnQMpTETKs48/EZNMgm0f6tunisflxYWKgyABMyipx10OIgjl3wUd95oF+xUU7+/AFaRJuxxHX/sbZiACvqMQI6/+HGQ+GGQ8zYy8AjzV6xt4VDV9UGLizIdvGEI7huq5KxPoPE3CTiuVQtdaXp8OuscVrfXoFlfehH/9zxxNsv+6niQplj3/ecTwz6yJfJTsSFOv+MXfH+oLZOjam14zudB5dEl1Mof9dYC63q5/HNp7TQrXsxHoqw2boWd22D7Zxm7XOw17z4NSF2N+M12ANv9ctvCTce4ocCMe6KJ3XEvpSxL0MzuxW+pNOfVb6iLSoeZQ38flwcl27UxXHR89f+3KKzJ+cA
  template:
    metadata:
      creationTimestamp: null
      name: clair-cm
      namespace: harbor

