apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clair
  namespace: harbor
spec:
  encryptedData:
    SCANNER_CLAIR_DATABASE_URL: AgArmrl17eeO3rmXvFO7WGZn/7FXIK77oeN9QMqXo4T7/c9cnmjy+i7TL8LIWVgmrTK4l/12Tij04iDSV4l+RTYN8Jm8o3rsd+cQM8y62ZwV9HJIGCt52/mKA4cauL37peu3AO98BekpudvXS002BEVWL1792QzQlYM/8i0eFUYFZ1y0GtvUg2h4OFQJnvnjos4AZv6DjD74MuLoMghrqs6n8puD6VioUzHe4kyqpPbzK4v3Dfr8ws65JujReFFd87ZH5iAz8mkhFgMl72auwMfl/xyLv+dxHFinf/mlquSIyuRdlr/3vCU4eAdBXEvHq5UEfJcoJCL2L2qKRdWw2hMyXG8G+1qL0U4zR1lFHzy1jqJR8zxFkpfFwoVG7Hg4zLFdjM2vJFIs80p/Mb1VYoQ0cg86Qb4gERfFyEFph0qeQbU52PB7wARh7RKYzrPfzVFJ3RYFpVoSB7GrY6zds+CiyCci4o0V0xbT9hz4ie5r+3SZO7cDl23BLvG1jWr4yZMvyRdXs7+yhNyDi5AoeXK8fKe4WTfloWPTJGmDyLsDCWzt2KDdmo1eM0YMfOb0uQ+7Buk226XARxOTc+GmKQKU8ORPab/xYP8ySvImpkk6KaopnJaAmXSgWH7vh5CIKkrW8N4rPjJhlN0TKA/UyqR1mED1LdBUoNf3xETrTi+8b97/TTlC1pgonAoz2wNHoKhmUPESVFVlnRxEo5OtuOcTcZZiYs123N89ir8m9f8wEnjdaDhjnE+ZSAMbdEke9BLex3ZKuCChS4SbQPndlemkzolI5+ym4hO5T6SebBUeSmnRlCz46iCCWQ==
  template:
    metadata:
      creationTimestamp: null
      name: clair
      namespace: harbor
    type: Opaque
status: {}

