apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jobservice
  namespace: harbor
spec:
  encryptedData:
    secret: AgCJpzBygz3UAu2goIZ/37Kzs/CYuHdBfeXwmawQ30edCfcPOT4DamDUPvY1MCfd/p5jAJkjw/6vnuHakcvPyphl/WX4eKTNe1au+IRu0EV9/HvFKcSXaGgzr6VeQsxww3oFqwsBbCB30RhpOkzjhf/La1CA3Q2Uk9dDEfe6JgFBnskErDrBsMRqjMicpAK67kWCTicM08Te4+VgHnrGthMRBgtiPr8zr4+7P0B00Fbk1fophpY1gAuQbZj1bbSAuScHolVu6ZRkFXLRxFQ9UJZ4IU2Kir7wbmDFs10IQdccN3f7+q7X8cxzpaCiSzxk7231rmzwcywHGRLaCnhD7XWHLCLyTWXnQD6sm7wk8m5LsdwfX/dI8y0pmhoHsHTois4cBdjYMaj3TiSiQcItd5sYUTJKF62Snvp3P+DHjZo22vfP+wCx3VEj7JyArBVI/Dl7Wim9PnzhE2Nu7u8hz+iXRSVjElnHfmFv9UhQVQEqvZOP018YLCYn8DGhg15pCcTt5LKlkPeUAu2CPOtIig4n1WywswfrYgtlGgYtXP+0XE0ldQp8DTgq4mGgrEg+3t+UYCulr2xhRmk5r5SACLht2irNPHgDuYOxSTqkgyV41Z6t0hGcosqV+Zp2kGxdYpKlCFh7aZvowZ/g13bUNO9/ZerpPc3ke9RNly+QFK4Faw52DZ9ViUZxyuBTZlN+Yr1Pw/Sa9J2N1P3/h98yyGtl
  template:
    metadata:
      creationTimestamp: null
      name: jobservice
      namespace: harbor
    type: Opaque

