apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jobservice-envvars
  namespace: harbor
spec:
  encryptedData:
    ENV_VAR: AgAJ5dnFW0XMa8RVXcki+33Jhvx6Y9f3ihFScH5SWKZ0mQ4mhOhgb3ZCOtvC4kp43kmkLX77Uh/wEWNEJqsDv8BazIJ6wAv0pL80DZc86ZpnCxWDZJ037PdUxd4YikbAz0xI26SrXf8hQhLBxFr4hTRd8g1+A2Rx2fwe2zHPlodjBl7Bs14mxRj5akHJ5tEVFNtezDQqVugcCvwPGIbpGjenHGJA8TJZKrMKTL41DqBqk4F4d6U1ycj3E+zP3hAVssJ64/HTUYuI2ryMyXoUAiKjM31R4Z5kGbjb+dQaMA6rRD1c6quOAvc+miACyJByGmVxVfJY2xzTkUl0nH1eM09GnTynPlDQ0gSSk5HjiT94lV2tYv4TPpOvzi203WZrPC6svuqyBw41pXQCdfJ+VdOjm47W6XS/m/PQ+NGt5ZJ9cATSg2+yA98cybBKIBzuWzZpp41jzXxi6Zo6JUmBIDSlkSUvn1fT82UaFUcw0LC9hsYN/CYfvnqBpadOjgC19YoNJkYdCNtqx71x3KbawTe7qWlHU5D6cWZkto5XG/Qbt2iX1HVtkvxeNnXia+5xi8ckPZYcXjJkyZZvPRMTZdOsLVMWL75Y++iLdy2CZK7Earj8BedP2/EbuqaKRULGDHBlzcfxfvhJXpB7cZRPZ4FVRCu4QVVVH6OpImJN8xPkT/AowOhZ88Y49ymGEN+VaGqDo+m2WXs=
  template:
    metadata:
      creationTimestamp: null
      name: jobservice-envvars
      namespace: harbor
    type: Opaque
status: {}

