apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry
  namespace: harbor
spec:
  encryptedData:
    REGISTRY_HTTP_SECRET: AgBxsuCaEFLGH5nahAYOPStTEJcPmL/OecTSfJQynSAyfMtHQZr4tSBCUN7eZ01hR2KXBReLgMp7yTnbEb+kmDVaDOL4aV/AV8VNWZRc5YmnYYxQ32dKE3YrglaBdXsMpsYqB9rprPZYXM1ll8/OJaOZMmr8x8XBXsyJoSVfy8ck2Ur7J1qwLwHlo8rOTQIwTSuZawR6wJqi6M1yCEpzrewQ+zcJFrRyCVuSb/pak3f7JSLLsb6OA3LrLxdBBgAHU8I4WwpvIdOzQfdtCANKEBxSeB0UioGPQvHDZak2Ao183QTqu0+A4rwufMgZS+dXgGYST8OVh0lPOs/XrdkuoVxGyQAcd3CroIiDJSfvsvtzuAv52SkE+1fFd0aYD7uKRtKXBZxIjjphYmERX7T8mP8xGZA15WppcptGcOItlOPsYusgR6V/55KrsqQW1XSl9ZGLq3yHE3tGkQ++V4aVVwdzmaMU7JMna5OZdGDYFsWUZhnu24AO7kUJ6wJnPhPwj3O3NXWtas6XcLmQ/vdBhhKuyhXP0DOip3E7e8rvNHafvs+POD4jxhKMRbW7GCkh08FQtJufQfgReBBcg56jXVSxks27+jLNTe/1J2qyQF0YZAKgBEuSQ61wsKyO8xDN/hEN79IUyCbOsVOLi0fapXTbe4yTX+P7nG0R8JB2iDIP3pZmljmGk4IbdzNMw6Xa/qJ84S2pyk8SG38hw7pkdGrX
    REGISTRY_REDIS_PASSWORD: AgAqnZaZxTTG2VMa93c5QAhMa+L0eV2g7YVH2Hpo8JPCQmcaKvEQcsSsTAuwC59xCb0SrSAbIbtg3F3rzCTiIi6/IEPpiATW+DELyecNJalPI3ghYmdVYvUsUUoyODNmln3gUPw/z8KL1XgqCWSkQD2vFX34GR6VKf0bfVFLO5ZfX7SytAl3kN8fs8wwp7rn/EwGJ6Re07Xsti8mHOEgrQthqEzIl01TDznEtH8lcHteDgW3lk/4ZGKPLMHW/pyULS+YAXeH1Hw2rkvq/msa1x1sF3eelf7eW5OshSB7zBI98Uce/WlJch/74Y6ctfbyX6nOJEa6t8ovkc8vVWApMQUGcQnWkqN99DTI1Rq3/XGNgEiw6gnEJAOvOka1+/+xY6hCWY9eQGFcqc9NB2/ha9XGMVXwsW4q1YA+jm18ncBlhxXykNW1Xt2HKG3eJ4qnQ3dD/k2XDjEhbhParzRNHPeyTaig9r5LrV5Knci2JIvP2h8AkaPQ6/HzfD1eoOHLbGJI2WZsZi9qrFxozvQR38MudiODaKO4Q84N+7c2EB3cjNJapdHs1Gj03KvQBvN2EkJ0Ye5fXSL2bOins7qzmlXm41qNEyKizXDP7jIZr06SxdyoxmxQra10EsnvacvkVhYFZvfz0Ck4CBd9WC+CG5Kr4zr2W26QAiGrrj+gg/dd6qtndH4Hpdo7bht2psT3qKw=
  template:
    metadata:
      creationTimestamp: null
      name: registry
      namespace: harbor
    type: Opaque

