apiVersion: v1
data:
  alertmanagers.yaml: ImFsZXJ0bWFuYWdlcnMiOgotICJodHRwX2NvbmZpZyI6CiAgICAiYmVhcmVyX3Rva2VuX2ZpbGUiOiAiL3Zhci9ydW4vc2VjcmV0cy9rdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3Rva2VuIgogICAgInRsc19jb25maWciOgogICAgICAiY2FfZmlsZSI6ICIvZXRjL3Byb21ldGhldXMvY29uZmlnbWFwcy9zZXJ2aW5nLWNlcnRzLWNhLWJ1bmRsZS9zZXJ2aWNlLWNhLmNydCIKICAgICAgInNlcnZlcl9uYW1lIjogImFsZXJ0bWFuYWdlci13aGVlbC5tb25pdG9yaW5nLXN0YWNrLnN2YyIKICAic2NoZW1lIjogImh0dHBzIgogICJzdGF0aWNfY29uZmlncyI6CiAgLSAiZG5zc3J2K193ZWIuX3RjcC5hbGVydG1hbmFnZXItb3BlcmF0ZWQubW9uaXRvcmluZy1zdGFjay5zdmMi
kind: Secret
metadata:
  name: thanos-ruler-alertmanagers-config
type: Opaque

