kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vault
spec:
  host: vault-new.baloise.dev
  to:
    kind: Service
    name: vault
    weight: 100
  port:
    targetPort: api-port
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
