apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: thanos-querier-tls
  labels:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: thanos-querier
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/version: 0.11.0
  name: thanos-querier
spec:
  ports:
  - name: web
    port: 9091
    targetPort: web
  - name: tenancy
    port: 9092
    targetPort: tenancy
  selector:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: thanos-querier
    app.kubernetes.io/name: thanos-query

