user-management-ui:
  angular-base:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/rewrite-target: /$2
      path: /user-management-ui(/|$)(.*)
    env:
      baseUrl: /user-management-ui/
      apiUrl: http://kubernetes.127.0.0.1.nip.io/user-management-service/
      keycloakUrl: http://kubernetes.127.0.0.1.nip.io/auth

user-management-service:
  ingress:
    enabled: true
    path: /user-management-service
  env:
    kcConnection:
      realm: usu
      auth:
        user: admin
        password: admin
      externalUrl: http://kubernetes.127.0.0.1.nip.io/auth
      internalUrl: http://um-keycloak/auth

keycloak:
  enabled: true
  ingress:
    enabled: true
    path: /
  env:
    db:
      vendor: postgres
      host: um-postgresql
      port: 5432
      database: keycloak
      user: postgres
      password: postgres
    admin:
      user: admin
      password: admin
    loggingLevelRoot: DEBUG

mariadb:
  architecture: standalone
  auth:
    database: keycloak
    username: keycloak
    password: keycloak
