kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kargo
spec:
  host: kargo.apps.baloise.dev
  to:
    kind: Service
    name: kargo-api
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
