apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana-wheel
spec:
  ingress:
    enabled: True
  serviceAccount:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-wheel-route","path":"/login/generic_oauth"}}'
  config:
    log:
      mode: "console"
      level: "warn"
    server:
      root_url: https://grafana-wheel-route-monitoring-stack.apps.okd.baloise.dev/
    security:
      admin_user: "root"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.anonymous:
      enabled: True
  dashboardLabelSelector:
    - matchExpressions:
        - { key: app, operator: In, values: [grafana] }
  # initResources:
  #   # Optionally specify initResources
  #   limits:
  #     cpu: 1000m
  #     memory: 512Mi
  #   requests:
  #     cpu: 250m
  #     memory: 128Mi
#  resources:
#    # Optionally specify container resources
#    limits:
#      cpu: 2000m
#      memory: 8000Mi
#    requests:
#      cpu: 100m
#      memory: 200Mi
