kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-proxy
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: monitoring-stack
roleRef:
  kind: ClusterRole
  name: grafana-proxy
  apiGroup: rbac.authorization.k8s.io
