{{ if .Values.ingress.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: moon-ui
spec:
  host: {{ .Values.ingress.host }}
  port:
    targetPort: {{ .Values.moonUI.port }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: moon-ui
    weight: 100
{{ end }}