{{- if .Values.createRole -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: moon
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
{{- end }}
