apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tekton-chatops-pipeline
spec:
  params:
    - name: comment
    - name: prid
    - name: reponame
    - name: prorg
    - name: apiurl
  tasks:
    - name: perform-chatops-command
      taskRef:
        name: tekton-chatops-gitopscli-task
      params:
        - name: comment
          value: $(params.comment)
        - name: prid
          value: $(params.prid)
        - name: reponame
          value: $(params.reponame)
        - name: prorg
          value: $(params.prorg)
        - name: apiurl
          value: $(params.apiurl)
