apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-chatops-rolebinding
subjects:
  - kind: ServiceAccount
    name: tekton-chatops-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-chatops-role
