---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-syncapps-trigger-template
spec:
  params:
    - name: reponame
    - name: rootorg
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: tekton-syncapps-pipeline-run-
        labels:
          app.kubernetes.io/instance: tekton-syncapps-pipeline-run
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
      spec:
        pipelineRef:
          name: tekton-syncapps-pipeline
        params:
          - name: reponame
            value: $(tt.params.reponame)
          - name: rootorg
            value: $(tt.params.rootorg)
