kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: portal-schemas
spec:
  host: usu-portal.apps.baloise.dev
  path: /schemas
  to:
    kind: Service
    name: {{ .Release.Name }}-portal-schemas
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None