kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: portal-adapter-ua-usm
spec:
  host: usu-portal.apps.baloise.dev
  path: /valuemation-portal-adapter
  to:
    kind: Service
    name: {{ .Release.Name }}-portal-adapter-usm
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None