apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
  - https://raw.githubusercontent.com/rook/rook/v1.8.8/deploy/examples/common.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.8.8/deploy/examples/crds.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.8.8/deploy/examples/operator-openshift.yaml
  - base/20_ceph-cluster.yaml
  - base/30_ceph-block-pool.yaml
  - base/35_ceph-filesystem.yaml
  - base/40_ceph-storage-class.yaml
  - base/45_cephfs-storage-class.yaml
  - base/50_ceph-volumesnapshotclass.yaml
  - base/55_cephfs-volumesnapshotclass.yaml

patchesStrategicMerge:
  - overlays/delete-ns-rook-ceph.yaml
  - overlays/delete-psp-rook.yaml
  - overlays/fix-rook-scc.yaml