apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: demo-client
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  client:
    clientId: demo-client
 #   secret: client-secret
    clientAuthenticatorType: client-secret
    protocol: openid-connect
