{{- if .Values.usuportal.ingress.enabled -}}
{{- $fullName := include "usu-portal.fullname" . -}}
{{- if and .Values.usuportal.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.usuportal.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.usuportal.ingress.annotations "kubernetes.io/ingress.class" .Values.usuportal.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-client
  labels:
    {{- include "usu-portal.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.usuportal.ingress.className }} 
  {{- if .Values.usuportal.ingress.tls }}
  tls:
    {{- range .Values.usuportal.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.usuportal.hostname }}
      http:
        paths:
          - path: /ui
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-client
                port:
                  name: http
{{- end }}
