apiVersion: v1
kind: Service
metadata:
  name: {{ include "usu-portal.fullname" . }}-client
  labels:
    {{- include "usu-portal.labels" . | nindent 4 }}
    app: usu-portal.client
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: usu-portal.client
