apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - args:
            $patch: delete