apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: akeyless-api-token
spec:
  data:
    - remoteRef:
        key: /akeyless/api-token
      secretKey: api-token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    deletionPolicy: Delete