apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
spec:
  ingress:
    enabled: True
  config:
    log:
      mode: "console"
      level: "debug"
    security:
      admin_user: "root"
      admin_password: "secret"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.anonymous:
      enabled: False
  dashboardLabelSelector:
    - matchExpressions:
        - {key: app, operator: In, values: [grafana]}