apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: grafanadatasource
spec:
  name: datasources.yaml
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: https://prometheus-wheel.monitoring-stack.svc:9093
      basicAuth: true
      basicAuthUser: internal
      basicAuthPassword: "e9K3fEGs4XuTeDKhrzc5X59NbWaZG5ku"
      isDefault: true
      version: 1
      orgId: 1
      editable: false
      jsonData:
        tlsSkipVerify: true
#        timeInterval: "5s"