apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCoWMPZxWnM2U1vi7a2BNNbFHfOhsM88uVr+YVMCf252jkgvCsHnX/ELBubgJyfW+imPw5wNKXTv87c+Cupcu7VAJLwduAdaniiJlanbbYBMPs9WrpaOpN6hiWTLRHQet6Ojl0R6TvW3Y4plmXMm656NYJ1JMeR7xzxs4tly4t1OCGcVU1Bb4tFnEhg4m5pKXmteHFrTUxPCxFkKpSeCITOj3sG+jOeFlOESzROJV0b0uguhuzlNyvHNuXxDvZlv84XzulWzmCSqf+65B7Jdf7TBhHn5sEFUUXVdVoEpDuK8OuWoBdFqPk2LttLFpaCJ/ysuk5jzotmtYbX3qGOs077dCal+4BxM7uKNCco7BxsEvPkQwa7A8weFadMYdLXyhJvJWckx7hMvelO/rkQkgf2y6gZTnRxmOwgS6CqdxGp311MooQhRb/nhpqr+6UwPip5vGbwoSK7CcWFgpiHEb5jAt1iM1oYMjmWOuZohpzEd3qFs3hTDF1yhh8HfvZwRbECkqO64MkSnj7yC1mmjDcfBhHDCvPObTT7tcXtIMiqYMr0/6BWfOj59LFRLpfk/qYxv/TknAMlS0PmfkNrb8jzscd9iyLwwZQrH/JOoSBedcWMod1cE6jVjLxZ+8ghrN8de56SjIRMcfwyCp2EElczdXzePK/gca3cR8IBoWjV4mEGBsx71FMpY9DtWgHnh+GqD3XSc2S2CF6mrjTkFkGIYe2SHZZ2Oa7S7FW/n1kCSt1woSK+oRzMwFm25c0n6K5lLrrwXfLw29whvAbo51CQfSxG9mb2kCjEn3EFSAI2RReaZKjuVACgy/aKB6pVVzU79zs3PlrREESWLyHq4w44nAFW8g==
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: noobaa
      name: cloud-credentials
      namespace: velero

