bitbucket:
  image:
    repository: docker.io/atlassian/bitbucket-server
    tag: 7.10
  replicaCount: 1
  network:
    http:
      servicePort: 7990
      ingress:
        host: bitbucket.baloise.dev
  resources:
    requests:
      memory: 3Gi
    limits:
      memory: 4Gi
  deployment:
    strategy:
      type: Recreate
  env:
    - name: SERVER_SCHEME
      value: https
  persistence:
    enabled: true
    size: 10Gi
    volumeMountPath: /var/atlassian/application-data/bitbucket
    storageClass: "ceph-block"

postgresql:
  securityContext:
    enabled: true
    fsGroup: 1001220000
    runAsUser: 1001220000
  postgresqlUsername: bitbucket
  postgresqlPassword: bitbucket
  postgresqlDatabase: bitbucket
