kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-operator
subjects:
- kind: ServiceAccount
  name: grafana-operator
  namespace: grafana-operator
roleRef:
  kind: ClusterRole
  name: grafana-operator
  apiGroup: rbac.authorization.k8s.io
