kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearch-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: elasticsearch-operator
  namespace: elasticsearch-operator
roleRef:
  kind: ClusterRole
  name: elasticsearch-operator
  apiGroup: rbac.authorization.k8s.io
