apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "usu-portal.fullname" . }}-adapter-ua
  labels:
    {{- include "usu-portal.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "usu-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "usu-portal.selectorLabels" . | nindent 8 }}
        app: usu-portal.adapter-ua
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 10 }}
      {{- end }}
      containers:
      - name: adapter-ua
        image: {{ .Values.usuportal.adapters.ua.image }}:{{ .Values.usuportal.adapters.ua.tag }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: 8022
        env:
          - name: spring.cloud.consul.enabled
            value: "false"
          - name: com.usu.keycloak.issuerUrls
            value: {{ .Values.usuportal.um.keycloakUrl | quote }}
          - name: com.usu.keycloak.authServerUrl
            value: "http://um-keycloak/auth"
          - name: usu.portal.vma.legacy-authorization.enabled
            value: {{ .Values.usuportal.adapters.ua.legacyAuth | quote }}
          - name: usu.portal.vma.legacy-authorization.header
            value: 'VMA_USER'
          - name: usu.portal.vma.pentaho-server-external-url
            value: {{ .Values.usuportal.adapters.ua.pentahoExternalUrl | quote }}
          - name: usu.portal.vma.pentaho-server-internal-url
            value: {{ .Values.usuportal.adapters.ua.pentahoInternalUrl | quote }}
