kind: Deployment
apiVersion: apps/v1
metadata:
  name: envoy-unauthenticated-prometheus-proxy
  labels:
    app: envoy-unauthenticated-prometheus-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-unauthenticated-prometheus-proxy
  template:
    metadata:
      labels:
        app: envoy-unauthenticated-prometheus-proxy
    spec:
      volumes:
        - name: config
          secret:
            secretName: envoy-unauthenticated-prometheus-proxy
      containers:
        - name: envoy
          image: >-
            envoyproxy/envoy@sha256:b29cafe337faa2db1da84de2276701d8b78314579b3dd1e7129b7b7f70cbae24
          ports:
            - containerPort: 9091
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /etc/envoy/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600