kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster
  namespace: portworx
  annotations:
    portworx.io/install-source: "https://install.portworx.com/?operator=true&mc=false&kbver=1.24.0&ns=portworx&oem=esse&user=33be41e6-79f3-11ea-97e6-f6e09c7a4e5e&b=true&s=%2Fdev%2Fnvme1n1&j=auto&c=px-cluster-931f56e1-a2ec-45dc-ba0f-b50a1c0bc38a&stork=true&csi=true&mon=true&tel=true&st=k8s&promop=true"
    portworx.io/is-openshift: "true"
    portworx.io/misc-args: "--oem esse"
spec:
  image: portworx/oci-monitor:2.12.1
  imagePullPolicy: Always
  kvdb:
    internal: true
  storage:
    devices:
    - /dev/nvme1n1
    journalDevice: auto
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: false
    prometheus:
      enabled: false
      exportMetrics: true
---
apiVersion: v1
kind: Secret
metadata:
  name: px-essential
  namespace: kube-system
data:
  px-essen-user-id: MzNiZTQxZTYtNzlmMy0xMWVhLTk3ZTYtZjZlMDljN2E0ZTVl
  px-osb-endpoint: aHR0cHM6Ly9weGVzc2VudGlhbHMucG9ydHdvcnguY29tL29zYi9iaWxsaW5nL3YxL3JlZ2lzdGVy