kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: sonarqube
spec:
  host: sonarqube.apps.baloise.dev
  to:
    kind: Service
    name: sonarqube-sonarqube
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None