apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: openshift-acme
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-acme
subjects:
- kind: ServiceAccount
  name: openshift-acme
  namespace: openshift-acme
