kind: ConfigMap
apiVersion: v1
metadata:
  name: letsencrypt-live
  namespace: openshift-acme
  labels:
    type: CertIssuer
  annotations:
    acme.openshift.io/priority: '100'
data:
  cert-issuer.types.acme.openshift.io: |
    acmeCertIssuer:
      account:
        contacts: []
        status:
          accountStatus: valid
          hash: '[178 91 41 76 180 222 182 158 160 10 76 60 243 17 57 4 128 27 96 21 229
            149 107 208 25 168 87 11 31 225 214 4 14 148 78 243 205 238 22 208 164 101
            3 202 110 101 154 37 242 28 249 206 221 193 63 53 42 60 152 19 140 21 214
            175]'
          ordersURL: ""
          uri: https://acme-v02.api.letsencrypt.org/acme/acct/83112192
      directoryURL: https://acme-v02.api.letsencrypt.org/directory
    secretName: letsencrypt-live
    type: ACME
