apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx-operator
resources:
  - github.com/ansible/awx-operator/config/default

patchesStrategicMerge:
  - overlays/delete-ns.yaml