apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gh-action-kargo
subjects:
  - kind: ServiceAccount
    namespace: gh-action-kargo
    name: gh-action-kargo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gh-action-kargo