apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
        -
          name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.11.0
          args:
            - --source=crd
            - --provider=cloudflare
            - --zone-id-filter=f4c572b9f198b76087f0ee74dbca43c2
            - --exclude-domains=incubator.baloise.dev
            - --exclude-domains=apps.baloise.dev
            - --txt-prefix=extdns.
            - --interval=20s
            - --events
            - --default-targets=142.132.241.113
            - --log-level=info
          env:
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api-key
                  name: cloudflare-api-key
            - name: CF_API_EMAIL
              value: "nikolas.philips@baloise.ch"
