apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
        -
          name: external-dns
          args:
            - --source=crd
            - --provider=cloudflare
            - --interval=20s
            - --events
            - --default-targets=49.12.17.221
            - --log-level=info
          env:
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api-key
                  name: cloudflare-api-key
            - name: CF_API_EMAIL
              value: "nikolas.philips@baloise.ch"
