kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devops-stack-kubevirt-view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: devops-stack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'kubevirt.io:view'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devops-stack-view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: devops-stack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'view'
---
