apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.1.2

resources:
  - base/argocd-ui-route.yaml
  - base/argocd-sealed-secret.yaml
  - base/default-appprojects.yaml
  - base/servicemonitors.yaml

patchesStrategicMerge:
  - overlays/argocd-application-controller.yaml
  - overlays/argocd-cm.yaml
  - overlays/argocd-dex-server.yaml
  - overlays/argocd-dex-server-sa.yaml
  - overlays/argocd-rbac-cm.yaml
  - overlays/argocd-redis.yaml
  - overlays/argocd-redis-ha-haproxy.yaml
  - overlays/argocd-server-deploy.yaml
  - overlays/argocd-repo-server-deploy.yaml
