apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "usu-portal.fullname" . }}-schemas
  labels:
    {{- include "usu-portal.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "usu-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "usu-portal.selectorLabels" . | nindent 8 }}
        app: usu-portal.schemas
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: schemas
        image: {{ .Values.portalApp.schemas.container.image }}:{{ .Values.portalApp.schemas.container.tag }}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 250m
        env:
          - name: CONSUL_TOKEN
            value: default
          - name: CONSUL_HOST
            value: 'consul-server'
          - name: CONSUL_PORT
            value: '8500'
          - name: CLIENT_BASE_PATH
            value: '/'
          - name: KEY_CLOAK_URL
            value: 'http://kubernetes.docker.internal/auth'
          - name: HELP_PAGE_URL
            value: 'https://google.com'
          - name: PROFILE_URL
            value: 'http://localhost/'
          - name: USER_MANAGEMENT_URL
            value: 'http://kubernetes.docker.internal/auth'
          - name: THEME_NAME
            value: 'green'
          - name: FALLBACK_LANGUAGE
            value: 'en'
          - name: BACKEND_HOST
            value: {{ include "usu-portal.fullname" . }}-backend-service
          - name: BACKEND_PORT
            value: '80'
          
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "usu-portal.fullname" . }}-schemas-service
  labels:
    {{- include "usu-portal.labels" . | nindent 4 }}
    app: usu-portal.schemas
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: usu-portal.schemas
