kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8sapi-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: k8sapi-sa
    namespace: postgres-operator
roleRef:
  kind: ClusterRole
  name: k8sapi-clusterrole
  apiGroup: rbac.authorization.k8s.io