kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8sapi-clusterrole
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]