apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  auth:
    externalIdentityProvider: false
    identityProviderClientId: che-public
    identityProviderImage: 'quay.io/eclipse/che-keycloak:nightly'
    identityProviderPassword: admin
    identityProviderPostgresSecret: che-identity-postgres-secret
    identityProviderRealm: che
    identityProviderSecret: che-identity-secret
    identityProviderURL: 'https://keycloak-che.apps.okd.baloise.dev'
    openShiftoAuth: true
    updateAdminPassword: true
  database:
    chePostgresDb: dbche
    chePostgresHostName: postgres
    chePostgresPort: '5432'
    chePostgresSecret: che-postgres-secret
    externalDb: false
  k8s:
    ingressDomain: che.apps.baloise.dev
  metrics:
    enable: false
  server:
    allowUserDefinedWorkspaceNamespaces: false
    cheDebug: 'false'
    cheFlavor: che
    cheHost: che-che.apps.okd.baloise.dev
    cheImageTag: nightly
    cheLogLevel: INFO
    devfileRegistryImage: 'quay.io/eclipse/che-devfile-registry:nightly'
    externalDevfileRegistry: false
    externalPluginRegistry: false
    gitSelfSignedCert: false
    pluginRegistryImage: 'quay.io/eclipse/che-plugin-registry:nightly'
    selfSignedCert: false
    tlsSupport: true
  storage:
    postgresPVCStorageClassName: ceph-block
    preCreateSubPaths: true
    pvcClaimSize: 5Gi
    pvcStrategy: per-workspace
    workspacePVCStorageClassName: cephfs
