apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  finalizers:
    - ingresscontroller.operator.openshift.io/finalizer-ingresscontroller
spec:
  defaultCertificate:
    name: default-ingress-tls
  replicas: 2