apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: alertmanager-wheel
    app.kubernetes.io/version: v0.38.1
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.alertmanager-wheel: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"alertmanager-wheel"}}
  name: alertmanager-wheel

