apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: alertmanager
  name: alertmanager
spec:
  endpoints:
  - interval: 30s
    port: web
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
      serverName: alertmanager-wheel.monitoring-stack.svc
  selector:
    matchLabels:
      alertmanager: wheel

