apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: contour-incubator
spec:
  namespace:
    name: contour
    removeOnDeletion: true
  networkPublishing:
    envoy:
      containerPorts:
        - name: http
          portNumber: 8080
        - name: https
          portNumber: 8443
      loadBalancer:
        providerParameters:
          type: AWS
        scope: External
      nodePorts:
        - name: http
          portNumber: 30080
        - name: https
          portNumber: 30443
      type: NodePortService
  replicas: 2