apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jenkins
spec:
  host: jenkins.apps.baloise.dev
  to:
    kind: Service
    name: jenkins-operator-http-jenkins
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
