kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
subjects:
  - kind: ServiceAccount
    name: default
    namespace: devops-stack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'kubevirt.io:view'
