apiVersion: v1
kind: Service
metadata:
  name: {{ include "usu-portal.fullname" . }}-backend
  labels:
    {{- include "usu-portal.labels" . | nindent 4 }}
    app: usu-portal.backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8120
      protocol: TCP
      name: http
  selector:
    app: usu-portal.backend
