kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: artifactory
  labels:
    app: {{ template "artifactory.name" . }}
    chart: {{ template "artifactory.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  host: artifactory-jcr.baloise.dev
  path: /
  to:
    kind: Service
    name: artifactory-jcr
    weight: 100
  port:
    targetPort: http-router
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None