{{- if and .Values.api.enabled .Values.api.oidc.enabled .Values.api.oidc.dex.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-dex-server
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.kargo: https://kargo.apps.baloise.dev/dex/callback
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.dexServer.labels" . | nindent 4 }}
{{- end }}
