global:
  openshift:
    enabled: false
  ingress:
    hostname: usu-portal.apps.okd.baloise.dev
usu-portal:
  consul:
    client:
      enabled: false
    connectInject:
      enabled: false
    server:
      replicas: 1
      disruptionBudget:
        enabled: false
      securityContext:
        runAsNonRoot: false
        runAsGroup: 0
        runAsUser: 0
        fsGroup: 0
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 100Mi
          cpu: 100m
    ui:
      enabled: false
    controller:
      enabled: false
  user-management:
    user-management-ui:
      angular-base:
        env:
          baseUrl: /user-management-ui/
          apiUrl: https://usu-portal.apps.okd.baloise.dev/user-management-service/
          keycloakUrl: https://usu-portal.apps.okd.baloise.dev/auth/
  user-management-service:
    env:
      kcConnection:
        externalUrl: "https://usu-portal.apps.okd.baloise.dev/auth/"
        internalUrl: "https://usu-portal.apps.okd.baloise.dev/auth/"
  ingress:
    hosts:
      - host: usu-portal.apps.okd.baloise.dev
