# SOURCE: https://install.portworx.com/?mc=false&kbver=1.17.1&oem=esse&user=33be41e6-79f3-11ea-97e6-f6e09c7a4e5e&b=true&c=px-cluster-8a8013b1-cee3-449b-95d7-6e02b603ba7b&osft=true&operator=true&stork=true&csi=true&lh=true&mon=true&st=k8s
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1alpha1
metadata:
  name: px-cluster-8a8013b1-cee3-449b-95d7-6e02b603ba7b
  annotations:
    portworx.io/install-source: "https://install.portworx.com/?mc=false&kbver=1.17.1&oem=esse&user=33be41e6-79f3-11ea-97e6-f6e09c7a4e5e&b=true&c=px-cluster-8a8013b1-cee3-449b-95d7-6e02b603ba7b&osft=true&operator=true&stork=true&csi=true&lh=true&mon=true&st=k8s"
    portworx.io/is-openshift: "true"
    portworx.io/misc-args: "--oem esse"
spec:
  image: portworx/oci-monitor:2.5.0
  imagePullPolicy: Always
  kvdb:
    internal: true
  storage:
    useAll: true
  secretsProvider: k8s
  stork:
    enabled: true
    image: openstorage/stork:2.3.3
  userInterface:
    enabled: true
    image: portworx/px-lighthouse:2.0.7
  autopilot:
    enabled: true
    image: portworx/autopilot:1.2.0
    providers:
      - name: default
        type: prometheus
        params:
          url: http://prometheus:9090
  monitoring:
    prometheus:
      exportMetrics: true
  featureGates:
    CSI: "true"
