apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: wheel-prometheus-tls
  labels:
    prometheus: wheel-prometheus
  name: wheel-prometheus
spec:
  ports:
  - name: metrics
    port: 9091
    targetPort: metrics
  - name: web
    port: 9093
    targetPort: web
  selector:
    app: prometheus
    prometheus: wheel-prometheus
  sessionAffinity: ClientIP

