apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: wheel
  name: wheel
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: prometheus
                  operator: In
                  values:
                    - wheel
            namespaces:
              - monitoring-stack
            topologyKey: kubernetes.io/hostname
          weight: 100
  alerting:
    alertmanagers:
      - apiVersion: v2
        bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        name: wheel-alertmanager
        namespace: monitoring-stack
        port: web
        scheme: https
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          serverName: alertmanager
  arbitraryFSAccessThroughSMs:
    deny: true
  containers:
    - args:
        - -provider=openshift
        - -https-address=:9093
        - -http-address=
        - -email-domain=*
        - -upstream=http://localhost:9090
        - -htpasswd-file=/etc/proxy/htpasswd/auth
        - -openshift-service-account=prometheus-wheel
        - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
        - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
        - -tls-cert=/etc/tls/private/tls.crt
        - -tls-key=/etc/tls/private/tls.key
        - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
        #- -cookie-secret-file=/etc/proxy/secrets/session_secret
        - --cookie-secret=SECRET
        - -openshift-ca=/etc/pki/tls/cert.pem
        - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - -skip-auth-regex=^/metrics
      env:
        - name: HTTP_PROXY
        - name: HTTPS_PROXY
        - name: NO_PROXY
      image: quay.io/openshift/okd-content@sha256:644bcaca0a108801e83f4c3585c267e069bd6d7975c4234cd6498d96693211b0
      name: prometheus-proxy
      ports:
        - containerPort: 9093
          name: web
      resources:
        requests:
          cpu: 1m
          memory: 20Mi
      terminationMessagePolicy: FallbackToLogsOnError
      volumeMounts:
        - mountPath: /etc/tls/private
          name: secret-prometheus-wheel-tls
#        - mountPath: /etc/proxy/secrets
#          name: secret-prometheus-k8s-proxy
        - mountPath: /etc/proxy/htpasswd
          name: secret-prometheus-wheel-htpasswd
    - args:
        - --secure-listen-address=0.0.0.0:9091
        - --upstream=http://127.0.0.1:9090
        - --tls-cert-file=/etc/tls/private/tls.crt
        - --tls-private-key-file=/etc/tls/private/tls.key
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
      image: quay.io/openshift/okd-content@sha256:1aa5bb03d0485ec2db2c7871a1eeaef83e9eabf7e9f1bc2c841cf1a759817c99
      name: kube-rbac-proxy
      ports:
        - containerPort: 9091
          name: metrics
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
      terminationMessagePolicy: FallbackToLogsOnError
      volumeMounts:
        - mountPath: /etc/tls/private
          name: secret-prometheus-wheel-tls
    - args:
        - sidecar
        - --prometheus.url=http://localhost:9090/
        - --tsdb.path=/prometheus
        - --grpc-address=[$(POD_IP)]:10901
        - --http-address=127.0.0.1:10902
        - --grpc-server-tls-cert=/etc/tls/grpc/tls.crt
        - --grpc-server-tls-key=/etc/tls/grpc/tls.key
        - --grpc-server-tls-client-ca=/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      name: thanos-sidecar
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
      volumeMounts:
        - mountPath: /etc/tls/grpc
          name: secret-prometheus-wheel-tls
  enforcedNamespaceLabel: namespace
  ignoreNamespaceSelectors: true
  image: quay.io/openshift/okd-content@sha256:279ce4bca3111edeb43485cfe9af9ddf1d5c449aba7f23d9c4f7bba3f7f723ee
  listenLocal: true
  nodeSelector:
    kubernetes.io/os: linux
  overrideHonorLabels: true
  overrideHonorTimestamps: true
  priorityClassName: system-cluster-critical
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
  retention: 15d
  # https://github.com/prometheus-operator/prometheus-operator/issues/2547#issuecomment-481494167
  ruleNamespaceSelector:
    matchLabels:
      client: cluster-infra
  ruleSelector: {}
  serviceMonitorNamespaceSelector:
    matchLabels:
      client: cluster-infra
  serviceMonitorSelector: {}
  secrets:
    - prometheus-wheel-tls
    - prometheus-wheel-htpasswd
  serviceAccountName: prometheus-wheel
  thanos:
    baseImage: quay.io/openshift/origin-thanos
    image: quay.io/openshift/okd-content@sha256:048ef6d2ea93c4a890c270b9b8623df624b7199c6ede15c7de78e0213caf9f00
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
    version: latest
  version: v2.15.2
