apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: wheel-prometheus
    app.kubernetes.io/version: v0.38.1
  name: wheel-prometheus

