apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "usu-portal.fullname" . }}-valuemation-portal-adapter
  labels:
    {{- include "usu-portal.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "usu-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "usu-portal.selectorLabels" . | nindent 8 }}
        app: usu-portal.valuemation-portal-adapter
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: valuemation-portal-adapter
        image: {{ .Values.portalApp.valuemationPortalPdapter.container.image }}:{{ .Values.portalApp.valuemationPortalPdapter.container.tag }}
        ports:
        - containerPort: 8011
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 1000m
        env:
          - name: spring.cloud.consul.host
            value: consul-server
          - name: spring.cloud.consul.port
            value: '8500'
          - name: spring.cloud.consul.discovery.acl-token
            value: default
          - name: spring.cloud.consul.discovery.hostname
            value: {{ include "usu-portal.fullname" . }}-valuemation-portal-adapter-service
          - name: spring.cloud.consul.discovery.port
            value: '80'
          - name: com.usu.keycloak.issuerUrls
            value: "https://usu-portal.apps.okd.baloise.dev/auth/"
          - name: com.usu.keycloak.authServerUrl
            value: "https://usu-portal.apps.okd.baloise.dev/auth/"
          - name: com.usu.keycloak.resource
            value: vm:valuemation-web
          - name: usu.portal.vm.webServiceClient-accessTokenPortal
            value: 'CYzOpmOTp17qG80Beo0mn.o42t&?zOI=+WJ+'
          - name: usu.portal.vm.dbguid
            value: 'd8503f50-bd77-4f0f-819d-84789c161539'
          - name: usu.portal.vm.vm-version
            value: '5.3'
          - name: usu.portal.vm.web.external-url
            value: 'http://moreu-dev.usu.usu.grp:58082/vmweb'
          - name: usu.portal.vm.web.internal-url
            value: 'http://moreu-dev.usu.usu.grp:58082/vmweb'
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "usu-portal.fullname" . }}-valuemation-portal-adapter-service
  labels:
    {{- include "usu-portal.labels" . | nindent 4 }}
    app: usu-portal.valuemation-portal-adapter
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8011
      targetPort: 8011
      protocol: TCP
      name: http
  selector:
    app: usu-portal.valuemation-portal-adapter
