apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "usu-portal.fullname" . }}-valuemation-analytics-portal-adapter
  labels:
    {{- include "usu-portal.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "usu-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "usu-portal.selectorLabels" . | nindent 8 }}
        app: usu-portal.valuemation-analytics-portal-adapter
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: valuemation-analytics-portal-adapter
        image: {{ .Values.portalApp.valuemationAnalytcsPortalAdapter.container.image }}:{{ .Values.portalApp.valuemationAnalytcsPortalAdapter.container.tag }}
        ports:
        - containerPort: 8022
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
        env:
          - name: spring.cloud.consul.host
            value: consul-server
          - name: spring.cloud.consul.port
            value: '8500'
          - name: spring.cloud.consul.discovery.acl-token
            value: default
          - name: spring.cloud.consul.discovery.hostname
            value: {{ include "usu-portal.fullname" . }}-valuemation-analytics-portal-adapter-service
          - name: spring.cloud.consul.discovery.port
            value: '80'
          - name: com.usu.keycloak.issuerUrls
            value: "https://usu-portal.apps.okd.baloise.dev/auth/"
          - name: com.usu.keycloak.authServerUrl
            value: "https://usu-portal.apps.okd.baloise.dev/auth/"
          - name: usu.portal.vma.legacy-authorization.enabled
            value: 'true'
          - name: usu.portal.vma.legacy-authorization.header
            value: 'VMA_USER'
          - name: usu.portal.vma.pentaho-server-external-url
            value: 'http://moreu-dev.usu.usu.grp:10082/console'
          - name: usu.portal.vma.pentaho-server-internal-url
            value: 'http://moreu-dev.usu.usu.grp:10082/console'
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "usu-portal.fullname" . }}-valuemation-analytics-portal-adapter-service
  labels:
    {{- include "usu-portal.labels" . | nindent 4 }}
    app: usu-portal.valuemation-analytics-portal-adapter
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8022
      targetPort: 8022
      protocol: TCP
      name: http
  selector:
    app: usu-portal.valuemation-analytics-portal-adapter