apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: harbor
  annotations:
    haproxy.router.openshift.io/timeout: 20m
  name: harbor
spec:
  host: {{ .Values.ingress.hosts.core }}
  path: /
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "common.names.fullname" . }}
    weight: 100
  wildcardPolicy: None