env:
  baseUrl: kubernetes.docker.internal
  keycloakUrl: kubernetes.docker.internal/auth
  apiUrl: kubernetes.docker.internal/api

extraEnv:
  TEST_ENV:
    value: "test value"

nameOverride: "example"

image:
  registry: docker.devops.usu.group
  repository: example-repo
  tag: latest
  pullPolicy: Always

ingress:
  enabled: true
  className: nginx
  hostname: kubernetes.docker.internal
  path: /example
  tls: true
  selfSigned: true
