apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-token
  namespace: tekton-chatopshandler
spec:
  encryptedData:
    token: AgAIscl71kBMlFxgy39/N4rN0Hydkd1p9WdYu0ASgUuSqZEJ8VMBxXG7Qjeu5OCIz1CKyz1WcE3F/XNwQ5is2UP+VH9WgIdAodlrFczLJTRElwGE4uolrROtrqFeX59pneQrDPpHIUlW3vfR6UD3OwDvefQxK6kHuFT+tByUeS203utTSEfufECeBoMnI/i7gZFbMMjruxtRuCm3h+sNGklr3A80W8rmUvnYcZ/A2P7V6wcQGcbd/ptG5Qw2GOZVGKqVnzfPdaqj+J7nEcoMR7HF5hENqzU1DZA5iFOtFt1an90WU6SPvuf//qoq0GO/Z1UtXlQeasVUIxF7DiuuUUj/FvdOj5OwJzEkA6RKPEEg+YTKHG0f1pCEd+qZ/EkVgBLGmEHdw9C3PPzrFx4xmvmDbBYF1HbS8d9OoCHvWIOGpU69Eo/ZgqyXZVBPLi36t30loIxKm2D3dO53k7CwcNHstvd2mAh33qo7JqyZ4cooaFgYTMnDSDkjStYr6qj8uAl5nOXxY09gBHwkEfRHFEMCpWLGk7oaXqxRRNmCxT3KGSUUp5Vs0hzUGIVKt+ZVEx6qDULCt6THjmhwqdQGZZWf8pMuLX18d1WQQRt6vaRFkzUKs8pDmfAXKfjiNmcD5GL1NMw5VE0Huzt2w0qaK6DRuDrwpin/FLbK/V32ZbTi9APRcUhyAaJM9BTLqKtWm5nOeH9hD2hCdFgasREVBngOOhu4FLIlXQbMSvqmnyjvw09hiJCx/ewp
  template:
    metadata:
      creationTimestamp: null
      name: github-token
      namespace: tekton-chatopshandler

