apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: tekton-chatops-greeting-task
spec:
  params:
    - name: prid
    - name: reponame
    - name: prorg
    - name: action
    - name: branchname
    - name: gitopscli-version
      default: 3.1.2
  stepTemplate:
    envFrom:
      - secretRef:
          name: github-token
  steps:
    - name: run-command
      image: baloise/gitopscli:$(tt.params.gitopscli-version)
      script: |
        if [ "$(tt.params.action)" = "opened" ]; then
          gitopscli add-pr-comment \
          --username incubator-tekton \
          --password $token \
          --git-provider github \
          --organisation $(tt.params.prorg) \
          --repository-name $(tt.params.reponame) \
          --text='Welcome to Baloise ChatOps based GitOps Bot.<br><br>If you want to enable preview environments for this PullRequest, comment with `/preview`.<br>If you want to disable the preview environment for this PR, comment with `/undeploy`.<br>If you need help or want to see the docs, comment with `/help`.<br><br>At the moment, preview environments do not get redeployed automatically. Simply rewrite `/preview` or contribute the feature.' \
          --pr-id $(tt.params.prid)
        elif [ "$(tt.params.action)" = "closed" ]; then
          gitopscli delete-preview \
          --username incubator-tekton \
          --password $token \
          --git-provider github \
          --git-user incubator-tekton \
          --git-email joachim.prinzbach+github-ttt-travis-bot@gmail.com \
          --organisation $(tt.params.prorg) \
          --repository-name $(tt.params.reponame) \
          --branch $(tt.params.branchname) \
          --create-pr \
          --auto-merge
        fi
