apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgBEGoPP53FjYZcRR2doYt6Ti5IRkc1oQPSi5VJNHH+9vVAHYRGdTIdcpp7vsIzhMNxf2mocZQ5hCmIuwb4/XiXGsW2gEeI8K/q9audodt96wvswZbJxCp083qy3n8YDoTeZEU7VulFuKfMzuY5zBasHV7JJcdPeyeRgibTGZT0YxhmhzQ8mAXSf1cbFWA+HWIW2SlHzWXm4czfh1uJGaGzMkkgyXz36Wwc3zX7BRrJiZYYmsH0+4TPAq/8+R01bF/tVDraomO0xPQ5f+PTi6UBZXwKr7FoF8dgsQ1rRn8bNeaSA2RkxnGilCC3O+kVOX94ALMnhV8YbukgeYDaRhJGnRQ502ZIqbtxkKSfdFnhUKn3cETglCJSUIsvJ4UcBYJ1T4NkcV3rRE8tQLv7/UIzl8UfI1VRyLLZp+PwwK7aJeoZjMDSlb6P4GSfGWJX0konogxa2d4lhLcfx29kYqTm2HSMyM7oE8De1Rjhd2guF9ykb6B8XI7CD8h+EvFkp2luov9bhLOvziSReQBotP1xMqOfnvt4lnAHsAT7Rg0hN8DGw3hmoA1niitjUit+rJj/fl3ScHJ2itlf/WnJzLrmsp+/s5mQ5p+01fPWUQFAWLMwRvvKmLHTdyK/0e1E3a9fgbcu0DnAeeWfYPWGKUTDHm3QyC+kTl//75f5yHRuiApcW6qm06YN6dRsE1kJ/WMTae6Z3ZH6bKq44nuE/eSW3YtMUO+Ts3e69ozOJRG71gCq3L0nK
  template:
    metadata:
      name: cloudflare-api-key
      namespace: cert-manager

