apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  annotations:
    release.openshift.io/create-only: 'true'
  name: cluster
spec:
  servingCerts:
    namedCertificates:
      - names:
          - api.incubator.baloise.dev
        servingCertificate:
          name: master-apiserver-tls
