apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-ingress-tls
  namespace: openshift-ingress
spec:
  secretName: default-ingress-tls
  dnsNames:
    - "baloise.dev"
    - "*.baloise.dev"
    - "*.apps.baloise.dev"
    - "*.incubator.baloise.dev"
    - "*.apps.incubator.baloise.dev"
    - "*.cloud.baloise.dev"
  issuerRef:
    name: cloudflare-lets-encrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
