apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: sealed-secrets-controller
          securityContext:
            $patch: delete
      securityContext:
        $patch: delete