name: Check and Update Argo CD Version

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Manual trigger

jobs:
  check_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine version to update to
        id: determine_version_to_update
        run: |
          echo Start
          current_version=$(grep -oP '(?<=ref=)v\d+\.\d+\.\d+' argocd/kustomization.yaml)
          echo current version: $current_version
          echo "::set-output name=current_version::$current_version"
          echo Releases
          releases=$(curl -s https://api.github.com/repos/argoproj/argo-cd/releases)
          
          is_rc="false"
          if [[ "$current_version" =~ rc[0-9]+$ ]]; then
          echo is_rc 
            is_rc="true"
          fi
          
          highest_stable_version=""
          next_rc_version=""
          
          for release in $(echo "$releases" | jq -r '.[].tag_name'); do
          echo release $release
            if [[ "$release" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(-.+)?$ ]]; then
              major="${BASH_REMATCH[1]}"
              minor="${BASH_REMATCH[2]}"
              patch="${BASH_REMATCH[3]}"
              prerelease="${BASH_REMATCH[4]}"
              
              if [[ "$prerelease" != "rc"* ]]; then
              echo no-prerelease
                if [[ -z $highest_stable_version ]] || (( major > $(echo $highest_stable_version | cut -d '.' -f 1) || ( major == $(echo $highest_stable_version | cut -d '.' -f 1) && minor > $(echo $highest_stable_version | cut -d '.' -f 2) ) || ( major == $(echo $highest_stable_version | cut -d '.' -f 1) && minor == $(echo $highest_stable_version | cut -d '.' -f 2) && patch > $(echo $highest_stable_version | cut -d '.' -f 3) ) )); then
                  highest_stable_version="$major.$minor.$patch"
                fi
              fi
              
              if [[ "$is_rc" == "true" && "$release" == "${current_version%.*}-"* ]]; then
              echo yes-prelease
                if [[ -z $next_rc_version ]] || [[ "$release" > "$next_rc_version" ]]; then
                  next_rc_version="$release"
                fi 
              fi
            fi
          done
          echo output
          if [[ "$is_rc" == "true" && "$next_rc_version" != "" ]]; then
            echo "::set-output name=version::$next_rc_version"
          else
            echo "::set-output name=version::$highest_stable_version"
          fi

      - name: Compare versions and update kustomization.yaml if needed
        if: steps.determine_version_to_update.outputs.version != steps.determine_version_to_update.outputs.current_version && steps.determine_version_to_update.outputs.version != null && steps.determine_version_to_update.outputs.current_version != null
        run: |
          sed -i "s/ref=${{ steps.determine_version_to_update.outputs.current_version }}/ref=${{ steps.determine_version_to_update.outputs.version }}/" argocd/kustomization.yaml
          echo "Updated Argo CD version in kustomization.yaml from ${{ steps.determine_version_to_update.outputs.current_version }} to ${{ steps.determine_version_to_update.outputs.version }}"
        working-directory: ${{ github.workspace }}

      - name: Commit and push if kustomization.yaml was updated
        if: steps.determine_version_to_update.outputs.version != steps.determine_version_to_update.outputs.current_version && steps.determine_version_to_update.outputs.version != null && steps.determine_version_to_update.outputs.current_version != null
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add argocd/kustomization.yaml
          git commit -m "Update Argo CD version to ${{ steps.determine_version_to_update.outputs.version }}"
          git push
